## SIB - P1

A Jupyter Notebook with examples of how to use the Dataset object.
18/09/2023

In [1]:
from si.data.dataset import Dataset
import numpy as np

# create a dataset
X = np.random.rand(150, 30)
y = np.random.randint(0, 2, 150)
dataset = Dataset(X, y)
dataset.shape()

(150, 30)

In [2]:
# get the X
dataset.X

array([[0.46518139, 0.12483023, 0.93213852, ..., 0.71630083, 0.33096077,
        0.56201817],
       [0.76764119, 0.41593913, 0.02001073, ..., 0.08493692, 0.50270083,
        0.20044385],
       [0.27226833, 0.71209096, 0.62918892, ..., 0.00613364, 0.00729392,
        0.57197232],
       ...,
       [0.47335762, 0.91449734, 0.23782842, ..., 0.78542307, 0.19073907,
        0.4439546 ],
       [0.44344981, 0.51144927, 0.17533238, ..., 0.02471561, 0.41283361,
        0.19786558],
       [0.77044332, 0.48881782, 0.09719459, ..., 0.4733016 , 0.66570295,
        0.73229083]])

In [3]:
#get the features names
dataset.features

['feat_0',
 'feat_1',
 'feat_2',
 'feat_3',
 'feat_4',
 'feat_5',
 'feat_6',
 'feat_7',
 'feat_8',
 'feat_9',
 'feat_10',
 'feat_11',
 'feat_12',
 'feat_13',
 'feat_14',
 'feat_15',
 'feat_16',
 'feat_17',
 'feat_18',
 'feat_19',
 'feat_20',
 'feat_21',
 'feat_22',
 'feat_23',
 'feat_24',
 'feat_25',
 'feat_26',
 'feat_27',
 'feat_28',
 'feat_29']

In [4]:
# has label?
dataset.has_label()

True

In [5]:
# print the label
dataset.y

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0])

In [6]:
# get classes
dataset.get_classes()

array([0, 1])

In [7]:
# statistics summary
dataset.summary()

feat_0    feat_1    feat_2    feat_3    feat_4    feat_5    feat_6  \
mean    0.486806  0.501809  0.509984  0.491343  0.532424  0.514177  0.494182   
median  0.475446  0.484531  0.548912  0.476968  0.540156  0.511506  0.492797   
min     0.008302  0.003359  0.009625  0.001095  0.006283  0.003460  0.003501   
max     0.998294  0.984555  0.992864  0.999080  0.970459  0.997577  0.993189   
var     0.078723  0.078691  0.080828  0.084627  0.077531  0.082427  0.083310   

          feat_7    feat_8    feat_9  ...   feat_20   feat_21   feat_22  \
mean    0.531632  0.487853  0.467405  ...  0.486368  0.500802  0.527746   
median  0.557158  0.489581  0.432367  ...  0.481000  0.499778  0.567559   
min     0.002811  0.001363  0.003277  ...  0.002937  0.026864  0.017144   
max     0.998080  0.989166  0.991442  ...  0.991937  0.992909  0.997966   
var     0.084753  0.083607  0.078543  ...  0.085333  0.078477  0.080205   

         feat_23   feat_24   feat_25   feat_26   feat_27   feat_28   feat_29  
mean    0.526308  0.513035  0.506486  0.547594  0.480648  0.505743  0.508955  
median  0.544460  0.515882  0.517642  0.589383  0.478571  0.505213  0.500506  
min     0.006992  0.000396  0.003800  0.003859  0.000316  0.007294  0.004561  
max     0.989581  0.998823  0.999428  0.997265  0.989182  0.999222  0.998807  
var     0.073150  0.082834  0.081650  0.086069  0.088088  0.082229  0.095745  

[5 rows x 30 columns]

In [8]:
from si.io.data_file import read_data_file

# read breast dataset from data file
breast_dataset = read_data_file('../datasets/breast_bin/breast-bin.data', sep=',', label=True)
breast_dataset.summary()

feat_0     feat_1     feat_2     feat_3     feat_4     feat_5  \
mean     4.417740   3.134478   3.207439   2.806867   3.216023   3.486409   
median   4.000000   1.000000   1.000000   1.000000   2.000000   1.000000   
min      1.000000   1.000000   1.000000   1.000000   1.000000   1.000000   
max     10.000000  10.000000  10.000000  10.000000  10.000000  10.000000   
var      7.917053   9.298082   8.819630   8.141527   4.896110  13.099601   

           feat_6     feat_7     feat_8  
mean     3.437768   2.866953   1.589413  
median   3.000000   1.000000   1.000000  
min      1.000000   1.000000   1.000000  
max     10.000000  10.000000  10.000000  
var      5.937114   9.311340   2.937284

In [9]:
breast_dataset.y

array([1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 0., 1., 1.,
       0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1.,
       1., 0., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0.,
       0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 0., 1., 0., 0.

In [10]:
print('Features', breast_dataset.features)
print('Label', breast_dataset.label)

Features ['feat_0', 'feat_1', 'feat_2', 'feat_3', 'feat_4', 'feat_5', 'feat_6', 'feat_7', 'feat_8']
Label y


In [11]:
# write the same fila with a different name
from si.io.data_file import write_data_file
write_data_file('../datasets/breast_bin/breast-bin_tabular.tsv', breast_dataset, sep='\t', label=True)

In [12]:
from si.io.csv_file import read_csv

# read iris dataset from data file
iris_dataset = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)
iris_dataset.summary()

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

In [13]:
iris_dataset.get_classes()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [14]:
# write the same file with a different name
from si.io.csv_file import write_csv
write_csv('../datasets/iris/iris_tabular.tsv', iris_dataset, sep='\t', features=True, label=True)

In [15]:
# random dataset
from si.data.dataset import Dataset
random_dataset = Dataset.from_random(150, 30, 4)
random_dataset.get_classes()

array([0, 1, 2, 3])

In [16]:
# from dataframe
import numpy as np
import pandas as pd

df = pd.DataFrame(np.random.rand(150, 30))
df_dataset = Dataset.from_dataframe(df)
df_dataset.X

array([[0.37328192, 0.30376297, 0.55606072, ..., 0.61164477, 0.58529107,
        0.85849804],
       [0.11450134, 0.66680255, 0.15815153, ..., 0.79707885, 0.90674921,
        0.41942974],
       [0.77647531, 0.03271738, 0.22218484, ..., 0.58996929, 0.8906747 ,
        0.51214323],
       ...,
       [0.47518704, 0.82464007, 0.3626203 , ..., 0.92117596, 0.80101011,
        0.46107106],
       [0.5512361 , 0.03193555, 0.18007827, ..., 0.29930119, 0.82236519,
        0.35077994],
       [0.68660198, 0.81117721, 0.12728584, ..., 0.09134611, 0.15578337,
        0.66446882]])

In [17]:
df_dataset.has_label()

False

In [18]:
df_w_nas = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)
df_w_nas.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, nan, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, nan],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, nan, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [nan, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, nan],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, nan],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [19]:
from copy import copy

df1 = copy(df_w_nas).dropna()
df1.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3

In [20]:
df2 = copy(df_w_nas).fillna(0)
df2.X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0. ],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 0. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [21]:
df2.remove_by_index(0)
df2.X

array([[4.9, 3. , 1.4, 0.2],
       [4.7, 0. , 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0. ],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 0. , 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [0. , 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0. ],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0. ],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3