### Notebook : Exercises 

In [51]:
from si.io.csv_file import read_csv
import numpy as np
import pandas as pd
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.f_classification import f_classification

#  Class 1

## Exercise 1: NumPy array Indexing/Slicing

In [52]:

# EXERCICIO 1

#1.1 - Loading the "iris.csv" using the appropriate method

path = r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv'

dataset = read_csv(path,features=True, label=True)



In [53]:
# 1.2) Select the penultimate independent variable

penultima_feature = dataset.X[:, -2]
dimensao = penultima_feature.shape

print("Penultimate Independent Variable:")
print(penultima_feature)
print("Dimension of the Resulting Array:")
print(dimensao)


Penultimate Independent Variable:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]
Dimension of the Resulting Array:
(150,)


In [54]:
#1.3 Select the last 10 samples and calculate the mean for each feature

last_10_samples = dataset.X[-10:]
mean = last_10_samples.mean(axis=0)

print("Last 10 Samples:")
print(last_10_samples)
print("Mean for Each Independent Variable/Feature:")
print(mean)

Last 10 Samples:
[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Mean for Each Independent Variable/Feature:
[6.45 3.03 5.33 2.17]


In [55]:
#1.4 Select samples with values less than or equal to 6 for all independent variables

selected_samples = dataset.X[(dataset.X <= 6).all(axis=1)]
print("Samples with Values less than or equal to 6 for All Independent Variables:")
print(selected_samples)
num_selected_samples = len(selected_samples)
print("Number of Samples:", num_selected_samples)

Samples with Values less than or equal to 6 for All Independent Variables:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5

In [56]:
# 1.5) Select samples with a class/label different from 'Irissetosa'

different_class_samples = dataset.X[dataset.y != 'Iris-setosa']
print("Samples with a Different Class/Label from 'Iris-setosa':")
print(different_class_samples)
num_different_class_samples = len(different_class_samples)
print("Number of Samples:", num_different_class_samples)

Samples with a Different Class/Label from 'Iris-setosa':
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.

### Optional: Use these methods to the script/notebook of Exercise 1.

In [3]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)



print("Before dropna:")
print("Dataset shape:", dataset.shape())
dataset.dropna()
print("\nAfter dropna:")
print("Dataset shape:", dataset.shape())

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)

print("\nBefore fillna with 0:")
print(dataset.summary())
print("\nFilling NaNs with 0:")
dataset.fillna(0)
print("\nAfter fillna with 0:")
print(dataset.summary())

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)

print("\nBefore removing sample by index:")
print("Dataset shape:", dataset.shape())
dataset.remove_by_index(3)
print("\nAfter removing sample at index 3:")
print("Dataset shape:", dataset.shape())



Before dropna:
Dataset shape: (150, 4)

After dropna:
Dataset shape: (134, 4)

Before fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.839041     3.049655      3.746259     1.213793
median      5.800000     3.000000      4.300000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.200000      6.900000     2.500000
var         0.697311     0.177534      3.144255     0.575258

Filling NaNs with 0:

After fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.683333     2.948000      3.671333     1.173333
median      5.700000     3.000000      4.250000     1.300000
min         0.000000     0.000000      0.000000     0.000000
max         7.900000     4.200000      6.900000     2.500000
var         1.563656     0.471296      3.356445     0.603556

Before removing sample by index:
Dataset shape: (150, 4)

After removing sample at index 3:
Dataset shape: (149, 4)


# Class 2
## Exercise 3: Test SelectPercentile

In [58]:
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)
dataset.X  

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [59]:
selector0 = SelectPercentile(f_classification, percentile = 0)
selector25 = SelectPercentile(f_classification, percentile = 0.25)
selector50 = SelectPercentile(f_classification, percentile = 0.50)
selector75 = SelectPercentile(f_classification, percentile = 0.75)
selector1 = SelectPercentile(f_classification, percentile = 1)


# do the fit_transform to all selectors and show the len of the features
transform0 = selector0.fit_transform(dataset)
print("Features with percentile 0: ", transform0.features)
print("Number of features with percentile 0: ", len(transform0.features))

print()

transform25 = selector25.fit_transform(dataset)
print("Features with percentile 25: ", transform25.features)
print("Number of features with percentile 25: ", len(transform25.features))

print()

transform50 = selector50.fit_transform(dataset)
print("Features with percentile 50: ", transform50.features)
print("Number of features with percentile 50: ", len(transform50.features))

print()

transform75 = selector75.fit_transform(dataset)
print("Features with percentile 75: ", transform75.features)
print("Number of features with percentile 75: ", len(transform75.features))

print()

transform1 = selector1.fit_transform(dataset)
print("Features with percentile 100: ", transform1.features)
print("Number of features with percentile 100: ", len(transform1.features))



Features with percentile 0:  ['sepal_width', 'sepal_length', 'petal_width', 'petal_length']
Number of features with percentile 0:  4

Features with percentile 25:  ['petal_length']
Number of features with percentile 25:  1

Features with percentile 50:  ['petal_width', 'petal_length']
Number of features with percentile 50:  2

Features with percentile 75:  ['sepal_length', 'petal_width', 'petal_length']
Number of features with percentile 75:  3

Features with percentile 100:  ['sepal_width', 'sepal_length', 'petal_width', 'petal_length']
Number of features with percentile 100:  4


# Class 3



## Exercise 4: Test Manhattan distance 




In [60]:
import numpy as np
from sklearn.metrics.pairwise import manhattan_distances as manhattan_distances_sklearn
from si.statistics.manhattan_distance import manhattan_distance


x = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [4, 5, 6]])
distance = manhattan_distance(x, y)

# sklearn distance

sklearn_distance = manhattan_distances_sklearn(x.reshape(1, -1), y)
assert np.allclose(distance, sklearn_distance)

print(f"Manhattan funtion = {distance}")
print(f"sklearn funtion = {sklearn_distance}")


Manhattan funtion = [0 9]
sklearn funtion = [[0. 9.]]


## Exercise 5: Test the PCA Class

In [61]:
# test PCA function

from si.decomposition.pca import PCA
from sklearn.decomposition import PCA as PCA_sklearn
from sklearn.preprocessing import StandardScaler

# load dataset
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

pca = PCA(n_components=2)
pca.fit_transform(dataset)

print('PCA:', pca.components)

print()

# sklearn PCA
pca_sklearn = PCA_sklearn(n_components=2)
pca_sklearn.fit_transform(dataset.X)
print('PCA Sklearn:', pca_sklearn.components_)



PCA: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]

PCA Sklearn: [[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]]



## Exercise 6: Implementing stratified splitting


In [62]:


from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
from si.model_selection.split import train_test_split



filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

print("Before stratified split:")

train1, test1 = train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train1.shape())
print("Test dataset shape:", test1.shape())
print("\n\n")

print("After stratified split:")

train, test = stratified_train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train.shape())
print("Test dataset shape:", test.shape())

# test with an example

from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
from si.model_selection.split import train_test_split



Before stratified split:
Train dataset shape: (120, 4)
Test dataset shape: (30, 4)



After stratified split:
Train dataset shape: (120, 4)
Test dataset shape: (30, 4)


## Exercise 7.1: Test RMSE

In [63]:

# test RMSE function

from si.metrics.rmse import rmse
import numpy as np

y_true = np.array([6, 5, 8])
y_pred = np.array([4, 3, 6])
rmse_value = rmse(y_true, y_pred)

print(f"RMSE = {rmse_value}")

# compare with sklearn RMSE

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse_sklearn = sqrt(mean_squared_error(y_true, y_pred))
assert np.allclose(rmse_value, rmse_sklearn)

print(f"RMSE sklearn = {rmse_sklearn}")





RMSE = 2.0
RMSE sklearn = 2.0


## Teste KNNRegressor

In [64]:
### KNN

from si.model_selection.split import train_test_split
from si.models.knn_regressor import KNNRegressor

cpu = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\cpu\\cpu.csv", sep = ",", features=True, label=True)

train, test = train_test_split(cpu, test_size=0.2, random_state=42)

# initialize the KNN_Classifier

knn = KNNRegressor(k=3)

# fit the model

knn.fit(train)

# evaluate the model on test data

score = knn.score(test)
print("Score RMSE:", score)

# compare with sklearn

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

knn_sklearn = KNeighborsRegressor(n_neighbors=3)
knn_sklearn.fit(train.X, train.y)
y_pred = knn_sklearn.predict(test.X)
score_sklearn = sqrt(mean_squared_error(test.y, y_pred))
print("Score RMSE sklearn:", score_sklearn)





Score RMSE: 81.36259969252635
Score RMSE sklearn: 81.36021813423898


## Optional – Categorical Naïve-Bayes

In [65]:
### test categoricalnaivebayes

from si.models.categorical_nb import CategoricalNB
from si.data.dataset import Dataset


X = np.array([[0, 1, 0], [1, 0, 1], [1, 1, 0], [0, 1, 1]])
y = np.array([0, 1, 0, 1])
  
dataset = Dataset(X, y)

model = CategoricalNB(smoothing=1)
model.fit(dataset)

predictions = model.predict(dataset)
error = model.score(dataset)

print("Predicted classes:", predictions)
print("Classification error:", error)

# compare with sklearn

from sklearn.naive_bayes import CategoricalNB as CategoricalNB_sklearn

model_sklearn = CategoricalNB_sklearn(alpha=1)
model_sklearn.fit(X, y)
predictions_sklearn = model_sklearn.predict(X)
error_sklearn = model_sklearn.score(X, y)

print("Predicted classes sklearn:", predictions_sklearn)
print("Classification error sklearn:", error_sklearn)




Predicted classes: [0 1 0 1]
Classification error: 1.0
Predicted classes sklearn: [0 1 0 1]
Classification error sklearn: 1.0


# Class 5
             
            

## Exercise 8: Test RidgeRegression with Least Squares 

In [66]:
# test ridge regression with least squares function

from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.data.dataset import Dataset
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
dataset_ = Dataset(X=X, y=y)

# fit the model
model = RidgeRegressionLeastSquares()
model.fit(dataset_)
print("Theta:", model.theta)
print("Theta Zero:", model.theta_zero)

# compute the score
print('Score:',model.score(dataset_))

print()
### test ridge regression with least squares

from si.models.ridge_regression import RidgeRegression
from si.data.dataset import Dataset
import numpy as np
from si.io.csv_file import read_csv
from si.metrics.mse import mse
from si.model_selection.split import *

from sklearn.linear_model import Ridge
model = Ridge()
    # scale data
X = (dataset_.X - np.nanmean(dataset_.X, axis=0)) / np.nanstd(dataset_.X, axis=0)
model.fit(X, dataset_.y)
print('Theta Sklearn:', model.coef_) # should be the same as theta
print('Theta Zeri Sklearn:', model.intercept_) # should be the same as theta_zero
print('Score:', mse(dataset_.y, model.predict(X))) # should be the same as score

Theta: [0.58823529 1.08145743]
Theta Zero: 8.5
Score: 0.07698961937716277

Theta Sklearn: [0.58823529 1.08145743]
Theta Zeri Sklearn: 8.5
Score: 0.07698961937716259


# Class 7

## Test Decision Tree

In [67]:
#use the iris dataset to test the decision tree classifier

from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.metrics.accuracy import accuracy
from si.model_selection.split import *

filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

#split the dataset into train and test
train, test = train_test_split(dataset, test_size=0.3, random_state=42)

#train the decision tree classifier using the train dataset

model = DecisionTreeClassifier(min_sample_split=3, max_depth=3, mode='entropy')
model.fit(train)

#print the tree
model.print_tree()

#evaluate the model on the test dataset

score = model.score(test)
print("Score:", score)




petal_length <= 1.9
	left: Iris-setosa
	right: petal_length <= 4.7
	  left: petal_width <= 1.5
	    left: Iris-versicolor
	    right: Iris-virginica
	  right: petal_length <= 5.1
	    left: petal_width <= 1.7
	      left: Iris-versicolor
	      right: Iris-virginica
	    right: Iris-virginica
Score: 0.9555555555555556


## Test VotingClassifier

In [68]:
#use the breast cancer dataset to test the voting classifier

from si.ensemble.voting_classifier import VotingClassifier
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.models.knn_classifier import KNNClassifier
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.metrics.accuracy import accuracy
from si.model_selection.split import *
from si.models.logistic_regression import LogisticRegression

filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

#split the dataset into train and test

train, test = train_test_split(dataset, test_size=0.3, random_state=42)

knn = KNNClassifier(k=3)
lg = LogisticRegression(l2_penalty=1, alpha=0.001, max_iter=1000)
dt = DecisionTreeClassifier(max_depth=5)

# initialize the Voting classifier
model = VotingClassifier([knn, lg, dt])

model.fit(train)

#evaluate the model on the test dataset

score = model.score(test)
print("Score:", score)

print("Predicted classes:", model.predict(test))



Score: 0.9760765550239234
Predicted classes: [1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]


## Exercise 9.2: Test the RandomForestClassifier class

In [69]:
### test random forest classifier

from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.metrics.accuracy import accuracy
from si.models.random_forest_classifier import RandomForestClassifier
    
# read iris dataset
data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv", sep=',', features=True, label=True)

# split dataset into train and test set
train_set, test_set = train_test_split(data, test_size=0.33, random_state=42)

# create random forest classifier
clf = RandomForestClassifier(n_estimators=10, max_depth=5, min_sample_split=2, mode='gini')

# fit classifier to train set
clf.fit(train_set)

# predict on test set
y_pred = clf.predict(test_set)

# calculate accuracy score
score = accuracy(test_set.y, y_pred)
print('Accuracy score: ', score)

# compare to sklearn

from sklearn.ensemble import RandomForestClassifier as skRandomForestClassifier
    
clf1 = skRandomForestClassifier(n_estimators=10, max_depth=5, min_samples_split=2)
clf1.fit(train_set.X, train_set.y)
y_pred = clf1.predict(test_set.X)
score = accuracy(test_set.y, clf1.predict(test_set.X))
print('Accuracy score sklearn: ', score)




Accuracy score:  0.9795918367346939
Accuracy score sklearn:  0.9795918367346939


## Exercise 10: Implementing the StackingClassifier ensemble

In [70]:
# test stacking classifier



from si.io.csv_file import read_csv
from si.model_selection.split import stratified_train_test_split
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.metrics.accuracy import accuracy
from si.ensemble.stacking_classifier import StackingClassifier

data = read_csv('C:\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv', sep=",",features=True,label=True)
train, test = stratified_train_test_split(data, test_size=0.20, random_state=42)

data = "C:\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv"  
breast=read_csv(data, sep=",",features=True,label=True)
train_data, test_data = stratified_train_test_split(breast, test_size=0.20, random_state=42)

#knnregressor
knn = KNNClassifier(k=3)
    
#logistic regression
LG=LogisticRegression(l2_penalty=1, alpha=0.001, max_iter=1000)

#decisiontreee
DT=DecisionTreeClassifier(min_sample_split=3, max_depth=3, mode='gini')

# Final Model (Choose a different model as the final model)
final_model = LogisticRegression(l2_penalty=1, alpha=0.001, max_iter=1000)

# Initialize StackingClassifier
models = [knn, LG, DT]
exercise = StackingClassifier(models, final_model)
exercise.fit(train_data)
print('Accuracy:', exercise.score(test_data))

# compare with sklearn
from sklearn.ensemble import StackingClassifier as SklearnStackingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# KNN
knn = KNeighborsClassifier(n_neighbors=3)

# Logistic Regression
LG = LogisticRegression(penalty='l2', C=1, solver='lbfgs', max_iter=1000)

# Decision Tree
DT = DecisionTreeClassifier(min_samples_split=3, max_depth=3, criterion='gini')

# Final Model (Choose a different model as the final model)
final_model = LogisticRegression(penalty='l2', C=1, solver='lbfgs', max_iter=1000)

# Initialize StackingClassifier
models = [('knn', knn), ('LG', LG), ('DT', DT)]
sklearn = SklearnStackingClassifier(estimators=models, final_estimator=final_model)
sklearn.fit(train_data.X, train_data.y)
y_pred = sklearn.predict(test_data.X)
print('Accuracy Sklearn:', accuracy_score(test_data.y, y_pred))



Accuracy: 0.9784172661870504
Accuracy Sklearn: 0.9784172661870504


## Test k_fold_cross_validation



In [71]:
# test k_cross_validation

from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.metrics.accuracy import accuracy
from si.models.knn_classifier import KNNClassifier
from si.model_selection.cross_validation import k_fold_cross_validation
from si.models.logistic_regression import LogisticRegression
import numpy as np

# read breast cancer dataset

data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv", sep=',', features=True, label=True)

lr = LogisticRegression()

# note that in a real application, you should leave a test set aside
scores = k_fold_cross_validation(model=lr, dataset=data, cv=5)
scores

print(f"Accuracy: {np.mean(scores):.2f} (+/- {np.std(scores):.2f})")







Accuracy: 0.97 (+/- 0.01)


## Teste grid_search_cv 

In [72]:
# test grid search

from si.io.csv_file import read_csv
from si.models.logistic_regression import LogisticRegression
from si.model_selection.cross_validation import k_fold_cross_validation
from si.model_selection.grid_search import grid_search_cv

# read breast cancer dataset

data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv", sep=',', features=True, label=True)

lg = LogisticRegression()
scores = k_fold_cross_validation(lg, data, cv=5)
scores

lg = LogisticRegression()

# parameter grid
parameter_grid = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001, 0.00001),
    'max_iter': (1000, 2000, 3000, 4000, 5000, 6000)
}

# cross validate the model
scores = grid_search_cv(lg,
                        data,
                        hyperparameter_grid=parameter_grid,
                        cv=3)

scores





{'scores': [0.9669540229885057,
  0.9655172413793104,
  0.9669540229885056,
  0.9655172413793104,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9655172413793104,
  0.9655172413793104,
  0.9655172413793104,
  0.9669540229885057,
  0.9640804597701149,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885056,
  0.9669540229885057,
  0.9655172413793104,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885056,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885057,
  0.9669540229885056,
  0.9669540229885057],
 'hyperparameters': [{'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000},
  {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 2000},
  {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 3000},
  {'l2_penalt

In [73]:
# best hyperparameters
scores['best_hyperparameters']

{'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}

In [74]:
# best score
scores['best_score']

0.9669540229885057

## Class 8

## Exercise 11: Test the randomized_search_cv function.

In [75]:
from si.models.logistic_regression import LogisticRegression
from si.data.dataset import Dataset
from si.model_selection.randomized_search import randomized_search_cv

num_samples = 600
num_features = 100
num_classes = 2

# random data
X = np.random.rand(num_samples, num_features)  
y = np.random.randint(0, num_classes, size=num_samples)  # classe aleatórios

dataset_ = Dataset(X=X, y=y)

#  features and class name
dataset_.features = ["feature_" + str(i) for i in range(num_features)]
dataset_.label = "class_label"

# initialize the Logistic Regression model
knn = LogisticRegression()

# parameter grid
parameter_grid_ = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001),
    'max_iter': (1000, 2000)
    }

# cross validate the model
results_ = randomized_search_cv(knn,
                              dataset_,
                              hyperparameter_grid=parameter_grid_,
                              cv=3,
                              n_iter=8)

# print the results
print(results_)

#get the best hyperparameters

best_hyperparameters = results_['best_hyperparameters']
print(f"Best hyperparameters: {best_hyperparameters}")

# get the best score
best_score = results_['best_score']
print(f"Best score: {best_score}")

{'scores': [0.5116666666666667, 0.5083333333333334, 0.5316666666666667, 0.49, 0.5283333333333333, 0.505, 0.52, 0.5283333333333333], 'hyperparameters': [{'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 2000}], 'best_hyperparameters': {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, 'best_score': 0.5316666666666667}
Best hyperparameters: {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}
Best score: 0.5316666666666667


In [76]:
# test using not random data

from si.models.logistic_regression import LogisticRegression
from si.data.dataset import Dataset
from si.model_selection.randomized_search import randomized_search_cv


X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.array([0, 1, 1, 0])

dataset_ = Dataset(X=X, y=y)

# initialize the Logistic Regression model
knn = LogisticRegression()

# parameter grid

parameter_grid_ = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001),
    'max_iter': (1000, 2000)
    }

# cross validate the model

results_ = randomized_search_cv(knn,
                                dataset_,
                                hyperparameter_grid=parameter_grid_,
                                cv=3,
                                n_iter=8)

# print the results

print(results_)

#get the best hyperparameters

best_hyperparameters = results_['best_hyperparameters']

print(f"Best hyperparameters: {best_hyperparameters}")	

best_score = results_['best_score']
print(f"Best score: {best_score}")


{'scores': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'hyperparameters': [{'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 2000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 1000}], 'best_hyperparameters': {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, 'best_score': 0.0}
Best hyperparameters: {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}
Best score: 0.0


In [77]:
# test randomized search cv sklearn

from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression as LogisticRegression_sklearn
from sklearn.metrics import accuracy_score
from si.data.dataset import Dataset
import numpy as np

num_samples = 600
num_features = 100
num_classes = 2

# random data
X = np.random.rand(num_samples, num_features)
y = np.random.randint(0, num_classes, size=num_samples)  # classe aleatórios

dataset_ = Dataset(X=X, y=y)

#  features and class name
dataset_.features = ["feature_" + str(i) for i in range(num_features)]
dataset_.label = "class_label"

# initialize the Logistic Regression model
knn = LogisticRegression_sklearn()

# parameter grid
parameter_grid_ = {
    'penalty': ['l1', 'l2'],
    'C': [1, 10],
    'max_iter': [1000, 2000]
    }

# cross validate the model

model = RandomizedSearchCV(knn, parameter_grid_, cv=3, n_iter=8)
model.fit(X, y)

# print the results
print(model.cv_results_)
print(model.best_params_)
print(model.best_score_)
print(model.best_estimator_)
print(model.best_index_)



{'mean_fit_time': array([0.        , 0.0246218 , 0.        , 0.00886099, 0.00033363,
       0.0126617 , 0.0003322 , 0.01408633]), 'std_fit_time': array([0.        , 0.01646289, 0.        , 0.00199649, 0.00047182,
       0.00170477, 0.0004698 , 0.00175666]), 'mean_score_time': array([0.        , 0.00066622, 0.        , 0.00029802, 0.        ,
       0.00066678, 0.        , 0.00033458]), 'std_score_time': array([0.        , 0.00047109, 0.        , 0.00042147, 0.        ,
       0.00047148, 0.        , 0.00047317]), 'param_penalty': masked_array(data=['l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_iter': masked_array(data=[1000, 1000, 2000, 2000, 1000, 1000, 2000, 2000],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10],

c:\Users\joana\anaconda3\envs\si_portefolio\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
12 fits failed out of a total of 24.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\joana\anaconda3\envs\si_portefolio\Lib\site-packages\sklearn\model_selection\_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\joana\anaconda3\envs\si_portefolio\Lib\site-packages\sklearn\base.py", line 1152, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\joana\anaconda3\envs\si_portefolio\Lib\site-p

# Class 9 

## Exercise 12: Dropout layer


In [78]:
# Test the layer with a random input 

from si.neural_networks.layers import DropoutLayer
import numpy as np

import numpy as np

np.random.seed(1)
x = np.random.randint(5, size=(1, 15))
print("x:", x)
# create the dropout layer
dropout_layer = DropoutLayer(0.5) #he dropout layer applies a dropout probability of 0.5
# test the dropout layer
print("output training:", dropout_layer.forward_propagation(x, training=True))
# print the mask
print("mask:", dropout_layer.mask)
print("output inference:", dropout_layer.forward_propagation(x, training=False))
    


x: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]
output training: [[0. 8. 0. 2. 0. 0. 0. 0. 8. 8. 0. 4. 8. 4. 0.]]
mask: [[0 1 0 1 0 1 0 0 1 1 0 1 1 1 0]]
output inference: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]


## Exercise 13: Test TanhActivation and SoftmaxActivation classes

In [79]:
# test the tanh activation function

import numpy as np

from si.neural_networks.activation import TanhActivation

np.random.seed(1)
x = np.random.randint(5, size=(1, 15))
print("x:", x)
print()

tanh_activation = TanhActivation()

print("output:", tanh_activation.forward_propagation(x, training=True))
print()
print("derivative:", tanh_activation.derivative(x))
print('\n', '\n', '\n')

x: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]

output: [[0.99505475 0.9993293  0.         0.76159416 0.99505475 0.
  0.         0.76159416 0.9993293  0.9993293  0.76159416 0.96402758
  0.9993293  0.96402758 0.9993293 ]]

derivative: [[0.00986604 0.00134095 1.         0.41997434 0.00986604 1.
  1.         0.41997434 0.00134095 0.00134095 0.41997434 0.07065082
  0.00134095 0.07065082 0.00134095]]

 
 



In [80]:

# test the softmax activation function

import numpy as np
from si.neural_networks.activation import SoftmaxActivation

np.random.seed(1)
x = np.random.randint(5, size=(1, 15))
print("x:", x)
print()

softmax_activation = SoftmaxActivation()

print("output:", softmax_activation.forward_propagation(x, training=True))
print()
print("derivative:", softmax_activation.derivative(x))

x: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]

output: [[0.05923281 0.16101147 0.00294903 0.00801629 0.05923281 0.00294903
  0.00294903 0.00801629 0.16101147 0.16101147 0.00801629 0.02179053
  0.16101147 0.02179053 0.16101147]]

derivative: [[0.05572428 0.13508678 0.00294033 0.00795203 0.05572428 0.00294033
  0.00294033 0.00795203 0.13508678 0.13508678 0.00795203 0.02131571
  0.13508678 0.02131571 0.13508678]]


## Exercise 14: Test CategoricalCrossEntropy Class

In [81]:
# categorical cross entropy loss function

from si.neural_networks.losses import CategoricalCrossEntropy
import numpy as np

y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
loss = CategoricalCrossEntropy()

print('Input:', X)
print()
print('Target:', y)
print()
print('Output:', loss.loss(y_true, y_pred))
print()
print('Gradiente:', loss.derivative(y_true, y_pred))



Input: [[0.26053659 0.28329719 0.28690184 ... 0.50884161 0.00125448 0.29467725]
 [0.11084116 0.70554298 0.43903072 ... 0.50949214 0.76749905 0.7950342 ]
 [0.87926686 0.33284972 0.15252811 ... 0.55162697 0.17750792 0.32603568]
 ...
 [0.88055144 0.15765703 0.16756591 ... 0.69642906 0.25893001 0.14851551]
 [0.73518418 0.83286755 0.97058767 ... 0.43583335 0.24905149 0.09716275]
 [0.35600837 0.7413659  0.73061723 ... 0.93447737 0.15197847 0.68075503]]

Target: [1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0
 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0
 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1
 0 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 0
 1 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1
 1 1 0 0 0 0 1 

## Exercise 15: Test Adam class

In [82]:
import numpy as np
from si.neural_networks.optimizers import Adam

adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8)

w = np.array([1, 2, 3])
grad_loss_w = np.array([1, 2, 3])

print('Input:', X)

print()

print('Target:', y)

print()

print('Output:', adam.update(w, grad_loss_w))



Input: [[0.26053659 0.28329719 0.28690184 ... 0.50884161 0.00125448 0.29467725]
 [0.11084116 0.70554298 0.43903072 ... 0.50949214 0.76749905 0.7950342 ]
 [0.87926686 0.33284972 0.15252811 ... 0.55162697 0.17750792 0.32603568]
 ...
 [0.88055144 0.15765703 0.16756591 ... 0.69642906 0.25893001 0.14851551]
 [0.73518418 0.83286755 0.97058767 ... 0.43583335 0.24905149 0.09716275]
 [0.35600837 0.7413659  0.73061723 ... 0.93447737 0.15197847 0.68075503]]

Target: [1 1 0 1 0 0 1 1 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 1 1 0 0 0 0 1 0 0
 1 1 0 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 1 1 0 1 0 1 0 1 1 1 0
 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 1 1 1 1 1 1 0
 1 1 1 0 1 1 1 1 0 0 1 1 0 1 1 1 1 0 1 1 0 1 1 0 0 0 1 1 1 0 1 1 1 0 0 1 1
 0 0 1 0 1 1 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 0 0
 1 0 1 1 1 1 0 0 0 1 1 1 0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 1 1 0 0 1 1 1 1 1 0 1 0 0 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 0 1 0 1
 1 1 0 0 0 0 1 

In [83]:
from si.neural_networks.optimizers import Adam

adam = Adam(learning_rate=0.001, beta_1=0.9, beta_2=0.999, epsilon=1e-8)

np.random.seed(42)
X = np.random.randint(0, 5, size=(1, 5))

np.random.seed(42)
y = np.random.random(5)

print(f'Input: {X}')
print()
print(f'Target: {y}')
print()

print(f'Output: {adam.update(X, y)}')

Input: [[3 4 2 4 4]]

Target: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]

Output: [[2.999 3.999 1.999 3.999 3.999]]


# Exercise 16 : Build, train and evaluate a neural network

In [84]:
# The training dataset has 32 features

from si.data.dataset import Dataset
import numpy as np

np.random.seed(32)
X = np.random.rand(400, 32)
y = np.random.randint(2, size=(400, 1))

dataset = Dataset(X, y)

print('Número de features:', dataset.shape()[1])

Número de features: 32


In [35]:
# split the dataset into train and test

train_dataset, test_dataset = stratified_train_test_split(dataset, test_size=0.2, random_state=42)

#shape of the train and test datasets

print('Shape of the train dataset:', train_dataset.shape())
print('Shape of the test dataset:', test_dataset.shape())


Shape of the train dataset: (321, 32)
Shape of the test dataset: (79, 32)


In [50]:
from si.data.dataset import Dataset
import numpy as np
from si.neural_networks.layers import Layer, DenseLayer, DropoutLayer
from si.neural_networks.neural_network import NeuralNetwork
from si.neural_networks.optimizers import SGD
from si.neural_networks.activation import ReLUActivation,SigmoidActivation
from si.neural_networks.losses import BinaryCrossEntropy
from si.model_selection.split import stratified_train_test_split
from si.metrics.accuracy import accuracy


# Train the NN for 100 epochs, with batchsize of 16 with a learning rate of 0.01. 
# Use the SGD optimizer, 
# use the BinaryCrossEntropy loss function 
# use accuracy metric. 
# Use the ReLU activation function for the hidden layers 
# the Sigmoid activation function for the output layer.



nn = NeuralNetwork(epochs=1000, batch_size=16, optimizer=SGD, learning_rate=0.01, verbose=False, loss=BinaryCrossEntropy, metric=accuracy)
nn.add(DenseLayer(32, (dataset.shape()[1],)))
nn.add(ReLUActivation())
nn.add(DenseLayer(16))
nn.add(ReLUActivation())
nn.add(DenseLayer(1))
nn.add(SigmoidActivation())
nn.fit(train_dataset)
print(nn.score(test_dataset))

0.4936708860759494


In [49]:
# do the same but with keras

from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.optimizers import SGD
from keras.losses import BinaryCrossentropy

model = Sequential()
model.add(Dense(32, input_dim=dataset.shape()[1]))
model.add(Activation('relu'))
model.add(Dense(16))
model.add(Activation('relu'))
model.add(Dense(1))
model.add(Activation('sigmoid'))

model.compile(optimizer=SGD(learning_rate=0.01),
                loss=BinaryCrossentropy(),
                metrics=['accuracy'])

model.fit(train_dataset.X, train_dataset.y, epochs=1000, batch_size=16, verbose=0)

score = model.evaluate(test_dataset.X, test_dataset.y, batch_size=16)
print("Score:", score[1])



5/5 [==============================] - 0s 2ms/step - loss: 2.4006 - accuracy: 0.4937
Score: 0.49367088079452515
