### Notebook : Exercises 

In [2]:
from si.io.csv_file import read_csv
import numpy as np
import pandas as pd
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.f_classification import f_classification

#  Class 1

## Exercise 1: NumPy array Indexing/Slicing

In [6]:

# EXERCICIO 1

#1.1 - Loading the "iris.csv" using the appropriate method

path = r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv'

dataset = read_csv(path,features=True, label=True)



In [4]:
# 1.2) Select the penultimate independent variable

penultima_feature = dataset.X[:, -2]
dimensao = penultima_feature.shape

print("Penultimate Independent Variable:")
print(penultima_feature)
print("Dimension of the Resulting Array:")
print(dimensao)


Penultimate Independent Variable:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]
Dimension of the Resulting Array:
(150,)


In [5]:
#1.3 Select the last 10 samples and calculate the mean for each feature

last_10_samples = dataset.X[-10:]
mean = last_10_samples.mean(axis=0)

print("Last 10 Samples:")
print(last_10_samples)
print("Mean for Each Independent Variable/Feature:")
print(mean)

Last 10 Samples:
[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Mean for Each Independent Variable/Feature:
[6.45 3.03 5.33 2.17]


In [5]:
#1.4 Select samples with values less than or equal to 6 for all independent variables

selected_samples = dataset.X[(dataset.X <= 6).all(axis=1)]
print("Samples with Values less than or equal to 6 for All Independent Variables:")
print(selected_samples)
num_selected_samples = len(selected_samples)
print("Number of Samples:", num_selected_samples)

Samples with Values less than or equal to 6 for All Independent Variables:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5

In [6]:
# 1.5) Select samples with a class/label different from 'Irissetosa'

different_class_samples = dataset.X[dataset.y != 'Iris-setosa']
print("Samples with a Different Class/Label from 'Iris-setosa':")
print(different_class_samples)
num_different_class_samples = len(different_class_samples)
print("Number of Samples:", num_different_class_samples)

Samples with a Different Class/Label from 'Iris-setosa':
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.

### Optional: Use these methods to the script/notebook of Exercise 1.

In [21]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)



print("Before dropna:")
print("Dataset shape:", dataset.shape())
dataset.dropna()
print("\nAfter dropna:")
print("Dataset shape:", dataset.shape())

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)

print("\nBefore fillna with 0:")
print(dataset.summary())
print("\nFilling NaNs with 0:")
dataset.fillna(0)
print("\nAfter fillna with 0:")
print(dataset.summary())

# read dataset
dataset = read_csv(r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris_missing_data.csv', features=True, label=True)

print("\nBefore removing sample by index:")
print("Dataset shape:", dataset.shape())
dataset.remove_by_index(3)
print("\nAfter removing sample at index 3:")
print("Dataset shape:", dataset.shape())



Before dropna:
Dataset shape: (150, 4)

After dropna:
Dataset shape: (134, 4)

Before fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.839041     3.049655      3.746259     1.213793
median      5.800000     3.000000      4.300000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.200000      6.900000     2.500000
var         0.697311     0.177534      3.144255     0.575258

Filling NaNs with 0:

After fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.683333     2.948000      3.671333     1.173333
median      5.700000     3.000000      4.250000     1.300000
min         0.000000     0.000000      0.000000     0.000000
max         7.900000     4.200000      6.900000     2.500000
var         1.563656     0.471296      3.356445     0.603556

Before removing sample by index:
Dataset shape: (150, 4)

After removing sample at index 3:
Dataset shape: (149, 4)


### Class 2
#### Exercise 3: Implementing SelectPercentile

In [8]:
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)
dataset.X  

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
selector0 = SelectPercentile(f_classification, percentile = 0)
selector25 = SelectPercentile(f_classification, percentile = 0.25)
selector50 = SelectPercentile(f_classification, percentile = 0.50)
selector75 = SelectPercentile(f_classification, percentile = 0.75)
selector1 = SelectPercentile(f_classification, percentile = 1)


# do the fit_transform to all selectors and show the len of the features
transform0 = selector0.fit_transform(dataset)
print("Number of features with percentile 0: ", len(transform0.features))


transform25 = selector25.fit_transform(dataset)
print("Number of features with percentile 25: ", len(transform25.features))


transform50 = selector50.fit_transform(dataset)
print("Number of features with percentile 50: ", len(transform50.features))

transform75 = selector75.fit_transform(dataset)
print("Number of features with percentile 75: ", len(transform75.features))

transform1 = selector1.fit_transform(dataset)
print("Number of features with percentile 100: ", len(transform1.features))



Number of features with percentile 0:  4
Number of features with percentile 25:  1
Number of features with percentile 50:  2
Number of features with percentile 75:  3
Number of features with percentile 100:  4


## Class 3



#### Exercise 4: Test Manhattan distance 




In [10]:
import numpy as np
from sklearn.metrics.pairwise import manhattan_distances as manhattan_distances_sklearn
from si.statistics.manhattan_distance import manhattan_distance


x = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [4, 5, 6]])
distance = manhattan_distance(x, y)

# sklearn distance

sklearn_distance = manhattan_distances_sklearn(x.reshape(1, -1), y)
assert np.allclose(distance, sklearn_distance)

print(f"Manhattan funtion = {distance}")
print(f"sklearn funtion = {sklearn_distance}")


Manhattan funtion = [0 9]
sklearn funtion = [[0. 9.]]


#### Exercise 5: Test the PCA Class

In [11]:
# test PCA function

from si.decomposition.pca import PCA
from sklearn.decomposition import PCA as PCA_sklearn
from sklearn.preprocessing import StandardScaler

# load dataset
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

pca = PCA(n_components=2)
pca.fit_transform(dataset)

print(pca.components)

# sklearn PCA
pca_sklearn = PCA_sklearn(n_components=2)
pca_sklearn.fit_transform(dataset.X)
print(pca_sklearn.components_)



[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]]



#### Exercise 6: Implementing stratified splitting


In [12]:


from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
from si.model_selection.split import train_test_split



filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

print("Before stratified split:")

train1, test1 = train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train1.shape())
print("Test dataset shape:", test1.shape())
print("\n\n")

print("After stratified split:")

train, test = stratified_train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train.shape())
print("Test dataset shape:", test.shape())


Before stratified split:
Train dataset shape: (120, 4)
Test dataset shape: (30, 4)



After stratified split:
Train dataset shape: (120, 4)
Test dataset shape: (30, 4)


#### Exercise 7: Implementing the KNNRegressor with RMSE

In [13]:
### RMSE

# test RMSE function

from si.metrics.rmse import rmse
import numpy as np

y_true = np.array([1, 2, 3])
y_pred = np.array([4, 5, 6])
rmse_value = rmse(y_true, y_pred)

print(f"RMSE = {rmse_value}")

# compare with sklearn RMSE

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse_sklearn = sqrt(mean_squared_error(y_true, y_pred))
assert np.allclose(rmse_value, rmse_sklearn)

print(f"RMSE sklearn = {rmse_sklearn}")



RMSE = 3.0
RMSE sklearn = 3.0


In [14]:
### KNN

from si.model_selection.split import train_test_split
from si.models.knn_regressor import KNNRegressor

cpu = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\cpu\\cpu.csv", sep = ",", features=True, label=True)

train, test = train_test_split(cpu, test_size=0.2, random_state=42)

# initialize the KNN_Classifier

knn = KNNRegressor(k=3)

# fit the model

knn.fit(train)

# evaluate the model on test data

score = knn.score(test)
print("Score RMSE:", score)




Score RMSE: 81.36259969252635


In [15]:

### KNN sklearn

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

knn_sklearn = KNeighborsRegressor(n_neighbors=3)
knn_sklearn.fit(train.X, train.y)
y_pred = knn_sklearn.predict(test.X)
score_sklearn = sqrt(mean_squared_error(test.y, y_pred))

print("Score RMSE sklearn:", score_sklearn)

Score RMSE sklearn: 81.36021813423898


#### Optional – Categorical Naïve-Bayes

In [16]:
### test categoricalnaivebayes

from si.models.categorical_nb import CategoricalNB
from si.data.dataset import Dataset


X = np.array([[0, 1, 0], [1, 0, 1], [1, 1, 0], [0, 1, 1]])
y = np.array([0, 1, 0, 1])
  
dataset = Dataset(X, y)

model = CategoricalNB(smoothing=1)
model.fit(dataset)

predictions = model.predict(dataset)
error = model.score(dataset)

print("Predicted classes:", predictions)
print("Classification error:", error)



Predicted classes: [0 1 0 1]
Classification error: 1.0


In [17]:
# test categoricalnaivebayes sklearn with the same dataset

from sklearn.naive_bayes import CategoricalNB as CategoricalNB_sklearn
from sklearn.metrics import accuracy_score

model_sklearn = CategoricalNB_sklearn(alpha=1)
model_sklearn.fit(X, y)
predictions_sklearn = model_sklearn.predict(X)
error_sklearn = accuracy_score(y, predictions_sklearn)

print("Predicted classes sklearn:", predictions_sklearn)
print("Classification error sklearn:", error_sklearn)



Predicted classes sklearn: [0 1 0 1]
Classification error sklearn: 1.0


## Class 5
             
            

#### Exercise 8: Test RidgeRegression with Least Squares 

In [18]:
# test ridge regression with least squares function

from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.data.dataset import Dataset
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
dataset_ = Dataset(X=X, y=y)

# fit the model
model = RidgeRegressionLeastSquares()
model.fit(dataset_)
print(model.theta)
print(model.theta_zero)

# compute the score
print(model.score(dataset_))

[0.58823529 1.08145743]
8.5
0.07698961937716277


In [19]:
### test ridge regression with least squares

from si.models.ridge_regression import RidgeRegression
from si.data.dataset import Dataset
import numpy as np
from si.io.csv_file import read_csv
from si.metrics.mse import mse
from si.model_selection.split import *

from sklearn.linear_model import Ridge
model = Ridge()
    # scale data
X = (dataset_.X - np.nanmean(dataset_.X, axis=0)) / np.nanstd(dataset_.X, axis=0)
model.fit(X, dataset_.y)
print(model.coef_) # should be the same as theta
print(model.intercept_) # should be the same as theta_zero
print(mse(dataset_.y, model.predict(X)))


[0.58823529 1.08145743]
8.5
0.07698961937716259


## Class 7

#### Test Decision Tree

In [6]:
#use the iris dataset to test the decision tree classifier

from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.metrics.accuracy import accuracy
from si.model_selection.split import *

filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

#split the dataset into train and test
train, test = train_test_split(dataset, test_size=0.3, random_state=42)

#train the decision tree classifier using the train dataset

model = DecisionTreeClassifier(min_sample_split=3, max_depth=3, mode='entropy')
model.fit(train)

#print the tree
model.print_tree()

#evaluate the model on the test dataset

score = model.score(test)
print("Score:", score)




petal_length <= 1.9
	left: Iris-setosa
	right: petal_length <= 4.7
	  left: petal_width <= 1.5
	    left: Iris-versicolor
	    right: Iris-virginica
	  right: petal_length <= 5.1
	    left: petal_width <= 1.7
	      left: Iris-versicolor
	      right: Iris-virginica
	    right: Iris-virginica
Score: 0.9555555555555556


#### Test VotingClassifier

In [15]:
#use the breast cancer dataset to test the voting classifier

from si.ensemble.voting_classifier import VotingClassifier
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.models.knn_classifier import KNNClassifier
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.metrics.accuracy import accuracy
from si.model_selection.split import *
from si.models.logistic_regression import LogisticRegression

filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

#split the dataset into train and test

train, test = train_test_split(dataset, test_size=0.3, random_state=42)

knn = KNNClassifier(k=3)
lg = LogisticRegression(l2_penalty=1, alpha=0.001, max_iter=1000)
dt = DecisionTreeClassifier(max_depth=5)

# initialize the Voting classifier
model = VotingClassifier([knn, lg, dt])

model.fit(train)

#evaluate the model on the test dataset

score = model.score(test)
print("Score:", score)

print("Predicted classes:", model.predict(test))



Score: 0.9760765550239234
Predicted classes: [1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.
 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0.
 0. 1. 1. 0. 1. 0. 0. 1. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0.
 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 0. 1. 1. 0. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 0.
 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 0. 1. 1. 0. 0. 0. 1. 1. 0.
 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]


#### Exercise 9: Test the RandomForestClassifier class

In [1]:
### test random forest classifier

from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.metrics.accuracy import accuracy
from si.models.random_forest_classifier import RandomForestClassifier
    
# read iris dataset
data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv", sep=',', features=True, label=True)

# split dataset into train and test set
train_set, test_set = train_test_split(data, test_size=0.33, random_state=42)

# create random forest classifier
clf = RandomForestClassifier(n_estimators=10, max_depth=5, min_sample_split=2, mode='gini')

# fit classifier to train set
clf.fit(train_set)

# predict on test set
y_pred = clf.predict(test_set)

# calculate accuracy score
score = accuracy(test_set.y, y_pred)
print('Accuracy score: ', score)

# compare to sklearn

from sklearn.ensemble import RandomForestClassifier as skRandomForestClassifier
    
clf1 = skRandomForestClassifier(n_estimators=10, max_depth=5, min_samples_split=2)
clf1.fit(train_set.X, train_set.y)
y_pred = clf1.predict(test_set.X)
score = accuracy(test_set.y, clf1.predict(test_set.X))
print('Accuracy score sklearn: ', score)




Accuracy score:  0.9795918367346939
Accuracy score sklearn:  0.9795918367346939


#### Exercise 10: Implementing the StackingClassifier ensemble

In [2]:
# test stacking classifier



from si.io.csv_file import read_csv
from si.model_selection.split import stratified_train_test_split
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.metrics.accuracy import accuracy
from si.ensemble.stacking_classifier import StackingClassifier

data = read_csv('C:\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv', sep=",",features=True,label=True)
train, test = stratified_train_test_split(data, test_size=0.20, random_state=42)

#knnregressor
knn = KNNClassifier(k=5)
    
#logistic regression
lr=LogisticRegression(l2_penalty=0.1, alpha=0.1, max_iter=1000)

#decisiontreee
dt=DecisionTreeClassifier(min_sample_split=2, max_depth=10, mode='gini')

#final model
final_model=KNNClassifier(k=5)
modelos=[knn,lr,dt]
exercise=StackingClassifier(modelos,final_model)
exercise.fit(train)
print(exercise.score(test))



0.9280575539568345


In [8]:
# test stacking classifier sklearn

from sklearn.ensemble import StackingClassifier as StackingClassifier_sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

#knnregressor
knn = KNeighborsClassifier(n_neighbors=5)

#logistic regression
lr=LogisticRegression(penalty="l2", C=0.1, max_iter=1000)

#decisiontreee
dt=DecisionTreeClassifier(min_samples_split=2, max_depth=10, criterion='gini')

#final model
final_model=KNeighborsClassifier(n_neighbors=5)
models=[('knn',knn),('lr',lr),('dt',dt)]
exercise=StackingClassifier_sklearn(estimators=models,final_estimator=final_model)
exercise.fit(train.X, train.y)
print(accuracy(test.y, exercise.predict(test.X)))

0.9784172661870504


#### Test k_fold_cross_validation



In [12]:
# test k_cross_validation

from si.io.csv_file import read_csv
from si.model_selection.split import train_test_split
from si.metrics.accuracy import accuracy
from si.models.knn_classifier import KNNClassifier
from si.model_selection.cross_validation import k_fold_cross_validation
from si.models.logistic_regression import LogisticRegression
import numpy as np

# read breast cancer dataset

data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv", sep=',', features=True, label=True)

lr = LogisticRegression()

# note that in a real application, you should leave a test set aside
scores = k_fold_cross_validation(model=lr, dataset=data, cv=5)
scores

print(f"Accuracy: {np.mean(scores):.2f} (+/- {np.std(scores):.2f})")







Accuracy: 0.97 (+/- 0.02)


#### Teste grid_search_cv 

In [15]:
# test grid search

from si.io.csv_file import read_csv
from si.models.logistic_regression import LogisticRegression
from si.model_selection.cross_validation import k_fold_cross_validation
from si.model_selection.grid_search import grid_search_cv

# read breast cancer dataset

data = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv", sep=',', features=True, label=True)

lg = LogisticRegression()
scores = k_fold_cross_validation(lg, data, cv=5)
scores

lg = LogisticRegression()

# parameter grid
parameter_grid = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001, 0.00001),
    'max_iter': (1000, 2000, 3000, 4000, 5000, 6000)
}

# cross validate the model
scores = grid_search_cv(lg,
                        data,
                        hyperparameter_grid=parameter_grid,
                        cv=3)

scores





{'l2_penalty': 10, 'alpha': 1e-05, 'max_iter': 6000}

In [16]:
# best hyperparameters
scores['best_hyperparameters']

{'l2_penalty': 10, 'alpha': 1e-05, 'max_iter': 6000}

In [17]:
# best score
scores['best_score']

0.9683908045977012

## Class 8

#### Exercise 11: Test the randomized_search_cv function.

In [ ]:
from si.models.logistic_regression import LogisticRegression
from si.data.dataset import Dataset
from si.model_selection.randomized_search import randomized_search_cv

num_samples = 600
num_features = 100
num_classes = 2

# random data
X = np.random.rand(num_samples, num_features)  
y = np.random.randint(0, num_classes, size=num_samples)  # classe aleatórios

dataset_ = Dataset(X=X, y=y)

#  features and class name
dataset_.features = ["feature_" + str(i) for i in range(num_features)]
dataset_.label = "class_label"

# initialize the Logistic Regression model
knn = LogisticRegression()

# parameter grid
parameter_grid_ = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001),
    'max_iter': (1000, 2000)
    }

# cross validate the model
results_ = randomized_search_cv(knn,
                              dataset_,
                              hyperparameter_grid=parameter_grid_,
                              cv=3,
                              n_iter=8)

# print the results
print(results_)

#get the best hyperparameters

best_hyperparameters = results_['best_hyperparameters']
print(f"Best hyperparameters: {best_hyperparameters}")

# get the best score
best_score = results_['best_score']
print(f"Best score: {best_score}")

{'scores': [0.45166666666666666, 0.4633333333333333, 0.43166666666666664, 0.4683333333333333, 0.44166666666666665, 0.405, 0.47833333333333333, 0.46166666666666667], 'hyperparameters': [{'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 1000}], 'best_hyperparameters': {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, 'best_score': 0.47833333333333333}
Best hyperparameters: {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}
Best score: 0.47833333333333333


In [ ]:
# test using not random data

from si.models.logistic_regression import LogisticRegression
from si.data.dataset import Dataset
from si.model_selection.randomized_search import randomized_search_cv


X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.array([0, 1, 1, 0])

dataset_ = Dataset(X=X, y=y)

# initialize the Logistic Regression model
knn = LogisticRegression()

# parameter grid

parameter_grid_ = {
    'l2_penalty': (1, 10),
    'alpha': (0.001, 0.0001),
    'max_iter': (1000, 2000)
    }

# cross validate the model

results_ = randomized_search_cv(knn,
                                dataset_,
                                hyperparameter_grid=parameter_grid_,
                                cv=3,
                                n_iter=8)

# print the results

print(results_)

#get the best hyperparameters

best_hyperparameters = results_['best_hyperparameters']

print(f"Best hyperparameters: {best_hyperparameters}")	

best_score = results_['best_score']
print(f"Best score: {best_score}")


{'scores': [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 'hyperparameters': [{'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, {'l2_penalty': 10, 'alpha': 0.001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 2000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.0001, 'max_iter': 1000}, {'l2_penalty': 1, 'alpha': 0.001, 'max_iter': 1000}, {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}], 'best_hyperparameters': {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}, 'best_score': 0.0}
Best hyperparameters: {'l2_penalty': 10, 'alpha': 0.0001, 'max_iter': 2000}
Best score: 0.0


In [ ]:
# test randomized search cv sklearn

from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression as LogisticRegression_sklearn
from sklearn.metrics import accuracy_score
from si.data.dataset import Dataset
import numpy as np

num_samples = 600
num_features = 100
num_classes = 2

# random data
X = np.random.rand(num_samples, num_features)
y = np.random.randint(0, num_classes, size=num_samples)  # classe aleatórios

dataset_ = Dataset(X=X, y=y)

#  features and class name
dataset_.features = ["feature_" + str(i) for i in range(num_features)]
dataset_.label = "class_label"

# initialize the Logistic Regression model
knn = LogisticRegression_sklearn()

# parameter grid
parameter_grid_ = {
    'penalty': ['l1', 'l2'],
    'C': [1, 10],
    'max_iter': [1000, 2000]
    }

# cross validate the model

model = RandomizedSearchCV(knn, parameter_grid_, cv=3, n_iter=8)
model.fit(X, y)

# print the results
print(model.cv_results_)
print(model.best_params_)
print(model.best_score_)
print(model.best_estimator_)
print(model.best_index_)



{'mean_fit_time': array([0.        , 0.01413933, 0.00033569, 0.01266567, 0.        ,
       0.01599773, 0.00033259, 0.0166111 ]), 'std_fit_time': array([0.        , 0.00229707, 0.00047474, 0.00169879, 0.        ,
       0.00283002, 0.00047036, 0.00255495]), 'mean_score_time': array([0.        , 0.00033315, 0.        , 0.        , 0.        ,
       0.00066733, 0.        , 0.00033331]), 'std_score_time': array([0.        , 0.00047115, 0.        , 0.        , 0.        ,
       0.00047188, 0.        , 0.00047137]), 'param_penalty': masked_array(data=['l1', 'l2', 'l1', 'l2', 'l1', 'l2', 'l1', 'l2'],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_max_iter': masked_array(data=[1000, 1000, 2000, 2000, 1000, 1000, 2000, 2000],
             mask=[False, False, False, False, False, False, False, False],
       fill_value='?',
            dtype=object), 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10],

c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
12 fits failed out of a total of 24.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
12 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\linear_model\_logistic.py", line 1461, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\linear_model\_logistic.py", line 449, in _check_s

## Class 9 

### Exercise 12: Dropout layer


In [ ]:
# Test the layer with a random input 

from si.neural_networks.layers import DropoutLayer
import numpy as np

import numpy as np
import si
#test the dropout layer
np.random.seed(1)
x = np.random.randint(5, size=(1, 15))
print("x:", x)
# create the dropout layer
dropout_layer = DropoutLayer(0.5) #he dropout layer applies a dropout probability of 0.5
# test the dropout layer
print("output training:", dropout_layer.forward_propagation(x, training=True))
# print the mask
print("mask:", dropout_layer.mask)
print("output inference:", dropout_layer.forward_propagation(x, training=False))
    


x: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]
output training: [[0. 8. 0. 2. 0. 0. 0. 0. 8. 8. 0. 4. 8. 4. 0.]]
mask: [[0. 2. 0. 2. 0. 2. 0. 0. 2. 2. 0. 2. 2. 2. 0.]]
output inference: [[3 4 0 1 3 0 0 1 4 4 1 2 4 2 4]]


### Exercise 13: Test TanhActivation and SoftmaxActivation classes

In [ ]:
# test the tanh activation function

import numpy as np

from si.neural_networks.activation import TanhActivation

np.random.seed(1)
x = np.random.randint(10, size=(1, 10))
print("x:", x)
print()

tanh_activation = TanhActivation()

print("output:", tanh_activation.forward_propagation(x, training=True))
print()
print("derivative:", tanh_activation.derivative(x))
print('\n', '\n', '\n')

x: [[5 8 9 5 0 0 1 7 6 9]]

output: [[0.9999092  0.99999977 0.99999997 0.9999092  0.         0.
  0.76159416 0.99999834 0.99998771 0.99999997]]

derivative: [[1.81583231e-04 4.50140598e-07 6.09199171e-08 1.81583231e-04
  1.00000000e+00 1.00000000e+00 4.19974342e-01 3.32610934e-06
  2.45765474e-05 6.09199171e-08]]

 
 



In [ ]:

# test the softmax activation function

import numpy as np
from si.neural_networks.activation import SoftmaxActivation

np.random.seed(1)
x = np.random.randint(10, size=(1, 10))
print("x:", x)
print()

softmax_activation = SoftmaxActivation()

print("output:", softmax_activation.forward_propagation(x, training=True))
print()
print("derivative:", softmax_activation.derivative(x))

x: [[5 8 9 5 0 0 1 7 6 9]]

output: [[7.07108730e-03 1.42026585e-01 3.86068285e-01 7.07108730e-03
  4.76446115e-05 4.76446115e-05 1.29511482e-04 5.22486607e-02
  1.92212081e-02 3.86068285e-01]]

derivative: [[7.02108703e-03 1.21855034e-01 2.37019564e-01 7.02108703e-03
  4.76423415e-05 4.76423415e-05 1.29494708e-04 4.95187382e-02
  1.88517533e-02 2.37019564e-01]]


#### Exercise 14: Test CategoricalCrossEntropy Class

In [ ]:
# categorical cross entropy loss function

from si.neural_networks.losses import CategoricalCrossEntropy
import numpy as np

y_true = np.array([[0, 1, 0], [0, 0, 1]])
y_pred = np.array([[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
loss = CategoricalCrossEntropy()
print(loss.loss(y_true, y_pred))
print()
print(loss.derivative(y_true, y_pred))



2.353878387381596

[[ -0.          -1.05263158  -0.        ]
 [ -0.          -0.         -10.        ]]


### Exercise 15: Test Adam class

In [ ]:
import numpy as np
from si.neural_networks.optimizers import Adam

adam = Adam(learning_rate=0.001)

w = np.array([1, 2, 3])
grad_loss_w = np.array([1, 2, 3])

print(adam.update(w, grad_loss_w))

[0.999 1.999 2.999]


# Exercise 16 : Build, train and evaluate a neural network

In [ ]:
# The training dataset has 32 features

from si.data.dataset import Dataset
import numpy as np

np.random.seed(32)
X = np.random.rand(400, 32)
y = np.random.randint(2, size=(400, 1))

dataset = Dataset(X, y)

print('Número de features:', dataset.shape()[1])

Número de features: 32


In [ ]:
# split the dataset into train and test

train_dataset, test_dataset = train_test_split(dataset, test_size=0.2, random_state=42)

#shape of the train and test datasets

print('Shape of the train dataset:', train_dataset.shape())
print('Shape of the test dataset:', test_dataset.shape())


Shape of the train dataset: (320, 32)
Shape of the test dataset: (80, 32)


In [ ]:
from si.data.dataset import Dataset
import numpy as np
from si.neural_networks.layers import Layer, DenseLayer, DropoutLayer
from si.neural_networks.neural_network import NeuralNetwork
from si.neural_networks.optimizers import SGD
from si.neural_networks.activation import ReLUActivation,SigmoidActivation
from si.neural_networks.losses import BinaryCrossEntropy
from si.model_selection.split import stratified_train_test_split
from si.metrics.accuracy import accuracy


# Train the NN for 100 epochs, with batchsize of 16 with a learning rate of 0.01. 
# Use the SGD optimizer, 
# use the BinaryCrossEntropy loss function 
# use accuracy metric. 
# Use the ReLU activation function for the hidden layers 
# the Sigmoid activation function for the output layer.



nn = NeuralNetwork(epochs=100, batch_size=16, optimizer=SGD, learning_rate=0.01, verbose=True, loss=BinaryCrossEntropy, metric=accuracy)
nn.add(DenseLayer(32, (dataset.shape()[1],)))
nn.add(ReLUActivation())
nn.add(DenseLayer(16))
nn.add(ReLUActivation())
nn.add(DenseLayer(1))
nn.add(SigmoidActivation())
nn.fit(train_dataset)

Epoch 1/100 - loss: 220.1206 - accuracy: 0.5781
Epoch 2/100 - loss: 219.3871 - accuracy: 0.5656
Epoch 3/100 - loss: 217.4933 - accuracy: 0.6000
Epoch 4/100 - loss: 216.2198 - accuracy: 0.5687
Epoch 5/100 - loss: 216.0575 - accuracy: 0.5813
Epoch 6/100 - loss: 215.9487 - accuracy: 0.5594
Epoch 7/100 - loss: 214.6500 - accuracy: 0.5719
Epoch 8/100 - loss: 211.2856 - accuracy: 0.6094
Epoch 9/100 - loss: 208.7744 - accuracy: 0.6094
Epoch 10/100 - loss: 205.4479 - accuracy: 0.6031
Epoch 11/100 - loss: 204.5813 - accuracy: 0.6656
Epoch 12/100 - loss: 204.3691 - accuracy: 0.6500
Epoch 13/100 - loss: 198.6170 - accuracy: 0.6281
Epoch 14/100 - loss: 193.2537 - accuracy: 0.6719
Epoch 15/100 - loss: 195.6992 - accuracy: 0.6438
Epoch 16/100 - loss: 193.3270 - accuracy: 0.6469
Epoch 17/100 - loss: 194.9498 - accuracy: 0.6312
Epoch 18/100 - loss: 187.0420 - accuracy: 0.6937
Epoch 19/100 - loss: 188.5031 - accuracy: 0.6844
Epoch 20/100 - loss: 189.8811 - accuracy: 0.6844
Epoch 21/100 - loss: 179.9737

In [ ]:
# test the model

print(nn.score(test_dataset))


0.3875
