In [1]:
from si.io.csv_file import read_csv
import numpy as np
import numpy as np
import pandas as pd
from si.data.dataset import Dataset
from si.io.csv_file import read_csv
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.f_classification import f_classification

###  Class 1
#### Exercise 1: NumPy array Indexing/Slicing

In [2]:

# EXERCICIO 1

#1.1 - Loading the "iris.csv" using the appropriate method

path = r'C:\Users\joana\OneDrive\Documentos\GitHub\si\datasets\iris\iris.csv'

dataset = read_csv(path,features=True, label=True)



In [3]:
# 1.2) Select the penultimate independent variable

penultima_feature = dataset.X[:, -2]
dimensao = penultima_feature.shape

print("Penultimate Independent Variable:")
print(penultima_feature)
print("Dimension of the Resulting Array:")
print(dimensao)


Penultimate Independent Variable:
[1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 1.5 1.6 1.4 1.1 1.2 1.5 1.3 1.4
 1.7 1.5 1.7 1.5 1.  1.7 1.9 1.6 1.6 1.5 1.4 1.6 1.6 1.5 1.5 1.4 1.5 1.2
 1.3 1.5 1.3 1.5 1.3 1.3 1.3 1.6 1.9 1.4 1.6 1.4 1.5 1.4 4.7 4.5 4.9 4.
 4.6 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.
 4.9 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.
 4.4 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3
 5.8 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.
 4.8 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9
 5.7 5.2 5.  5.2 5.4 5.1]
Dimension of the Resulting Array:
(150,)


In [4]:
#1.3 Select the last 10 samples and calculate the mean for each feature

last_10_samples = dataset.X[-10:]
mean = last_10_samples.mean(axis=0)

print("Last 10 Samples:")
print(last_10_samples)
print("Mean for Each Independent Variable/Feature:")
print(mean)

Last 10 Samples:
[[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Mean for Each Independent Variable/Feature:
[6.45 3.03 5.33 2.17]


In [5]:
#1.4 Select samples with values less than or equal to 6 for all independent variables

selected_samples = dataset.X[(dataset.X <= 6).all(axis=1)]
print("Samples with Values less than or equal to 6 for All Independent Variables:")
print(selected_samples)
num_selected_samples = len(selected_samples)
print("Number of Samples:", num_selected_samples)

Samples with Values less than or equal to 6 for All Independent Variables:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5

In [6]:
# 1.5) Select samples with a class/label different from 'Irissetosa'

different_class_samples = dataset.X[dataset.y != 'Iris-setosa']
print("Samples with a Different Class/Label from 'Iris-setosa':")
print(different_class_samples)
num_different_class_samples = len(different_class_samples)
print("Number of Samples:", num_different_class_samples)

Samples with a Different Class/Label from 'Iris-setosa':
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]
 [5.7 2.8 4.5 1.3]
 [6.3 3.3 4.7 1.6]
 [4.9 2.4 3.3 1. ]
 [6.6 2.9 4.6 1.3]
 [5.2 2.7 3.9 1.4]
 [5.  2.  3.5 1. ]
 [5.9 3.  4.2 1.5]
 [6.  2.2 4.  1. ]
 [6.1 2.9 4.7 1.4]
 [5.6 2.9 3.6 1.3]
 [6.7 3.1 4.4 1.4]
 [5.6 3.  4.5 1.5]
 [5.8 2.7 4.1 1. ]
 [6.2 2.2 4.5 1.5]
 [5.6 2.5 3.9 1.1]
 [5.9 3.2 4.8 1.8]
 [6.1 2.8 4.  1.3]
 [6.3 2.5 4.9 1.5]
 [6.1 2.8 4.7 1.2]
 [6.4 2.9 4.3 1.3]
 [6.6 3.  4.4 1.4]
 [6.8 2.8 4.8 1.4]
 [6.7 3.  5.  1.7]
 [6.  2.9 4.5 1.5]
 [5.7 2.6 3.5 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.4 3.7 1. ]
 [5.8 2.7 3.9 1.2]
 [6.  2.7 5.1 1.6]
 [5.4 3.  4.5 1.5]
 [6.  3.4 4.5 1.6]
 [6.7 3.1 4.7 1.5]
 [6.3 2.3 4.4 1.3]
 [5.6 3.  4.1 1.3]
 [5.5 2.5 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.1 3.  4.6 1.4]
 [5.8 2.6 4.  1.2]
 [5.  2.3 3.3 1. ]
 [5.6 2.7 4.2 1.3]
 [5.7 3.  4.2 1.2]
 [5.7 2.9 4.2 1.3]
 [6.2 2.9 4.3 1.3]
 [5.1 2.5 3.  1.1]
 [5.7 2.8 4.

Optional: You can add examples of how to use these methods to the script/notebook of Exercise 1.

In [7]:
from si.data.dataset import Dataset


print("Before dropna:")
print("Dataset shape:", dataset.shape())
dataset.dropna()
print("\nAfter dropna:")
print("Dataset shape:", dataset.shape())

print("\nBefore fillna with 0:")
print(dataset.summary())
print("\nFilling NaNs with 0:")
dataset.fillna(0)
print("\nAfter fillna with 0:")
print(dataset.summary())

print("\nBefore removing sample by index:")
print("Dataset shape:", dataset.shape())
dataset.remove_by_index(3)
print("\nAfter removing sample at index 3:")
print("Dataset shape:", dataset.shape())



Before dropna:
Dataset shape: (150, 4)

After dropna:
Dataset shape: (150, 4)

Before fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

Filling NaNs with 0:

After fillna with 0:
        sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.054000      3.758667     1.198667
median      5.800000     3.000000      4.350000     1.300000
min         4.300000     2.000000      1.000000     0.100000
max         7.900000     4.400000      6.900000     2.500000
var         0.681122     0.186751      3.092425     0.578532

Before removing sample by index:
Dataset shape: (150, 4)

After removing sample at index 3:
Dataset shape: (149, 4)


### Class 2
#### Exercise 3: Implementing SelectPercentile

In [8]:
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)
dataset.X  

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
selector0 = SelectPercentile(f_classification, percentile = 0)
selector25 = SelectPercentile(f_classification, percentile = 0.25)
selector50 = SelectPercentile(f_classification, percentile = 0.50)
selector75 = SelectPercentile(f_classification, percentile = 0.75)
selector1 = SelectPercentile(f_classification, percentile = 1)


# do the fit_transform to all selectors and show the len of the features
transform0 = selector0.fit_transform(dataset)
print("Number of features with percentile 0: ", len(transform0.features))


transform25 = selector25.fit_transform(dataset)
print("Number of features with percentile 25: ", len(transform25.features))


transform50 = selector50.fit_transform(dataset)
print("Number of features with percentile 50: ", len(transform50.features))

transform75 = selector75.fit_transform(dataset)
print("Number of features with percentile 75: ", len(transform75.features))

transform1 = selector1.fit_transform(dataset)
print("Number of features with percentile 100: ", len(transform1.features))



Number of features with percentile 0:  4
Number of features with percentile 25:  1
Number of features with percentile 50:  2
Number of features with percentile 75:  3
Number of features with percentile 100:  4


## Class 3



#### Exercise 4: Test Manhattan distance 




In [10]:
import numpy as np
from sklearn.metrics.pairwise import manhattan_distances as manhattan_distances_sklearn
from si.statistics.manhattan_distance import manhattan_distance


x = np.array([1, 2, 3])
y = np.array([[1, 2, 3], [4, 5, 6]])
distance = manhattan_distance(x, y)

# sklearn distance

sklearn_distance = manhattan_distances_sklearn(x.reshape(1, -1), y)
assert np.allclose(distance, sklearn_distance)

print(f"Manhattan funtion = {distance}")
print(f"sklearn funtion = {sklearn_distance}")


Manhattan funtion = [0 9]
sklearn funtion = [[0. 9.]]


#### Exercise 5: Test the PCA Class

In [11]:
# test PCA function

from si.decomposition.pca import PCA
from sklearn.decomposition import PCA as PCA_sklearn
from sklearn.preprocessing import StandardScaler

# load dataset
filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

pca = PCA(n_components=2)
pca.fit_transform(dataset)

print(pca.components)

# sklearn PCA
pca_sklearn = PCA_sklearn(n_components=2)
pca_sklearn.fit_transform(dataset.X)
print(pca_sklearn.components_)



[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [-0.65653988 -0.72971237  0.1757674   0.07470647]]
[[ 0.36158968 -0.08226889  0.85657211  0.35884393]
 [ 0.65653988  0.72971237 -0.1757674  -0.07470647]]



#### Exercise 6: Implementing stratified splitting


In [12]:


from si.data.dataset import Dataset
from si.model_selection.split import stratified_train_test_split
from si.model_selection.split import train_test_split



filename = "\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\iris\\iris.csv"
dataset = read_csv(filename= filename, sep = ',', features = True, label = True)

print("Before stratified split:")

train1, test1 = train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train1.shape())
print("Test dataset shape:", test1.shape())
print("\n\n")

print("After stratified split:")

train, test = stratified_train_test_split(dataset, test_size=0.2, random_state=42)
print("Train dataset shape:", train.shape())
print("Test dataset shape:", test.shape())


Before stratified split:
Train dataset shape: (120, 4)
Test dataset shape: (30, 4)



After stratified split:
Train dataset shape: (30, 4)
Test dataset shape: (30, 4)


#### Exercise 7: Implementing the KNNRegressor with RMSE

In [13]:
### RMSE

# test RMSE function

from si.metrics.rmse import rmse
import numpy as np

y_true = np.array([1, 2, 3])
y_pred = np.array([4, 5, 6])
rmse_value = rmse(y_true, y_pred)

print(f"RMSE = {rmse_value}")

# compare with sklearn RMSE

from sklearn.metrics import mean_squared_error
from math import sqrt

rmse_sklearn = sqrt(mean_squared_error(y_true, y_pred))
assert np.allclose(rmse_value, rmse_sklearn)

print(f"RMSE sklearn = {rmse_sklearn}")



RMSE = 3.0
RMSE sklearn = 3.0


In [14]:
### KNN

from si.model_selection.split import train_test_split
from si.models.knn_regressor import KNNRegressor

cpu = read_csv("\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\cpu\\cpu.csv", sep = ",", features=True, label=True)

train, test = train_test_split(cpu, test_size=0.2, random_state=42)

# initialize the KNN_Classifier

knn = KNNRegressor(k=3)

# fit the model

knn.fit(train)

# evaluate the model on test data

score = knn.score(test)
print("Score RMSE:", score)




Score RMSE: 81.36259969252635


In [15]:

### KNN sklearn

from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from math import sqrt

knn_sklearn = KNeighborsRegressor(n_neighbors=3)
knn_sklearn.fit(train.X, train.y)
y_pred = knn_sklearn.predict(test.X)
score_sklearn = sqrt(mean_squared_error(test.y, y_pred))

print("Score RMSE sklearn:", score_sklearn)

Score RMSE sklearn: 81.36021813423898


#### Optional – Categorical Naïve-Bayes

In [16]:
### test categoricalnaivebayes

from si.models.categorical_nb import CategoricalNB
from si.data.dataset import Dataset


X = np.array([[0, 1, 0], [1, 0, 1], [1, 1, 0], [0, 1, 1]])
y = np.array([0, 1, 0, 1])
  
dataset = Dataset(X, y)

model = CategoricalNB(smoothing=1)
model.fit(dataset)

predictions = model.predict(dataset)
error = model.score(dataset)

print("Predicted classes:", predictions)
print("Classification error:", error)



Predicted classes: [0 1 0 1]
Classification error: 0.0
Predicted classes: [0 1 0 1]
Classification error: 0.0


In [17]:
# test categoricalnaivebayes sklearn with the same dataset

from sklearn.naive_bayes import CategoricalNB as CategoricalNB_sklearn
from sklearn.metrics import accuracy_score

model_sklearn = CategoricalNB_sklearn(alpha=1)
model_sklearn.fit(X, y)
predictions_sklearn = model_sklearn.predict(X)
error_sklearn = accuracy_score(y, predictions_sklearn)

print("Predicted classes sklearn:", predictions_sklearn)
print("Classification error sklearn:", error_sklearn)



Predicted classes sklearn: [0 1 0 1]
Classification error sklearn: 1.0


## Class 5
             
            

#### Exercise 8: Test RidgeRegression with Least Squares 

In [18]:
# test ridge regression with least squares function

from si.models.ridge_regression_least_squares import RidgeRegressionLeastSquares
from si.data.dataset import Dataset
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.dot(X, np.array([1, 2])) + 3
dataset_ = Dataset(X=X, y=y)

# fit the model
model = RidgeRegressionLeastSquares()
model.fit(dataset_)
print(model.theta)
print(model.theta_zero)

# compute the score
print(model.score(dataset_))

[0.58823529 1.08145743]
8.5
0.07698961937716277


In [22]:
### test ridge regression with least squares

from si.models.ridge_regression import RidgeRegression
from si.data.dataset import Dataset
import numpy as np
from si.io.csv_file import read_csv
from si.metrics.mse import mse
from si.model_selection.split import *

from sklearn.linear_model import Ridge
model = Ridge()
    # scale data
X = (dataset_.X - np.nanmean(dataset_.X, axis=0)) / np.nanstd(dataset_.X, axis=0)
model.fit(X, dataset_.y)
print(model.coef_) # should be the same as theta
print(model.intercept_) # should be the same as theta_zero
print(mse(dataset_.y, model.predict(X)))


[0.58823529 1.08145743]
8.5
0.07698961937716259


## Class 7

#### Exercise 9: Test the RandomForestClassifier class

In [24]:
### test random forest classifier

from si.models.random_forest_classifier import RandomForestClassifier
from si.data.dataset import Dataset
import numpy as np

X = np.array([[1, 1], [1, 2], [2, 2], [2, 3]])
y = np.array([0, 1, 1, 0])

dataset_ = Dataset(X=X, y=y)

# fit the model

model = RandomForestClassifier(n_estimators=100, max_depth=2)

model.fit(dataset_)

# compute the score

print(model.score(dataset_))

# test random forest classifier sklearn

from sklearn.ensemble import RandomForestClassifier as RandomForestClassifier_sklearn

model_sklearn = RandomForestClassifier_sklearn(n_estimators=100, max_depth=2)

model_sklearn.fit(X, y)

print(model_sklearn.score(X, y))



ImportError: cannot import name 'Literal' from 'typing' (c:\Users\joana\anaconda3\envs\si\lib\typing.py)

#### Exercise 10: Implementing the StackingClassifier ensemble

In [25]:
# test stacking classifier



from si.io.csv_file import read_csv
from si.model_selection.split import stratified_train_test_split
from si.models.knn_classifier import KNNClassifier
from si.models.logistic_regression import LogisticRegression
from si.models.decision_tree_classifier import DecisionTreeClassifier
from si.metrics.accuracy import accuracy
from si.ensemble.stacking_classifier import StackingClassifier

data = read_csv('C:\\Users\\joana\\OneDrive\\Documentos\\GitHub\\si\\datasets\\breast_bin\\breast-bin.csv', sep=",",features=True,label=True)
train, test = stratified_train_test_split(data, test_size=0.20, random_state=42)

#knnregressor
knn = KNNClassifier(k=5)
    
#logistic regression
lr=LogisticRegression(l2_penalty=0.1, alpha=0.1, max_iter=1000)

#decisiontreee
dt=DecisionTreeClassifier(min_sample_split=2, max_depth=10, mode='gini')

#final model
final_model=KNNClassifier(k=5)
modelos=[knn,lr,dt]
exercise=StackingClassifier(modelos,final_model)
exercise.fit(train)
print(exercise.score(test))



ImportError: cannot import name 'Literal' from 'typing' (c:\Users\joana\anaconda3\envs\si\lib\typing.py)

In [26]:
# test stacking classifier sklearn

from sklearn.ensemble import StackingClassifier as StackingClassifier_sklearn
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

#knnregressor
knn = KNeighborsClassifier(n_neighbors=5)

#logistic regression
lr=LogisticRegression(penalty='l2', C=0.1, max_iter=1000)

#decisiontreee
dt=DecisionTreeClassifier(min_samples_split=2, max_depth=10, criterion='gini')

#final model
final_model=KNeighborsClassifier(n_neighbors=5)
models=[('knn',knn),('lr',lr),('dt',dt)]
exercise=StackingClassifier_sklearn(estimators=models,final_estimator=final_model)
exercise.fit(train.X, train.y)
print(accuracy(test.y, exercise.predict(test.X)))

c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\model_selection\_split.py:680: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=5.
  UserWarning,
c:\Users\joana\anaconda3\envs\si\lib\site-packages\sklearn\model_selection\_validation.py:1097: RuntimeWarning: Number of classes in training fold (87) does not match total number of classes (101). Results may not be appropriate for your use case. To fix this, 

NameError: name 'accuracy' is not defined

## Class 8

#### Exercise 11: Test the randomized_search_cv function.